<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC" ignored="0" name="批阅作业" tests="1" failures="1" timestamp="26 十二月 2018 13:10:40 GMT" time="37.597" errors="0">
  <testcase name="piyue" time="11.318" classname="com.edu.teach_test.Piyue_Test">
    <failure type="java.lang.AssertionError" message="待验收错误 expected [0] but found [null]">
      <![CDATA[java.lang.AssertionError: 待验收错误 expected [0] but found [null]
at com.edu.teach_test.Piyue_Test.piyue(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- piyue -->
</testsuite> <!-- 批阅作业 -->
